{"uuid": "f9746701-a251-46f2-aed7-5f73995e0922", "children": ["ff69ade8-3611-45b5-a949-66cef3334b86", "01c0abe5-e58a-43f5-8a0c-4d6240e44094", "c83d0b29-2b99-4d70-86cd-c95837debdbf", "0576c6f2-0895-464b-9838-9509b4e6cff4", "4f68ee2e-666e-488e-b6b6-c0f379b5def2", "eee8195a-a4f5-424e-b00b-b06df65dc6eb"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f94e6ee8fa0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "trace": "  File \"/home/manikanta/PycharmProjects/pythonProject_info/venv/lib/python3.8/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/manikanta/PycharmProjects/pythonProject_info/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1129, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/manikanta/PycharmProjects/pythonProject_info/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 901, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/manikanta/PycharmProjects/pythonProject_info/Opsis_Plateful/conftest.py\", line 15, in setup\n    driver = webdriver.Remote('http://127.0.0.1:4723/wd/hub', desired_cap)\n  File \"/home/manikanta/PycharmProjects/pythonProject_info/venv/lib/python3.8/site-packages/appium/webdriver/webdriver.py\", line 230, in __init__\n    super().__init__(\n  File \"/home/manikanta/PycharmProjects/pythonProject_info/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 286, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/manikanta/PycharmProjects/pythonProject_info/venv/lib/python3.8/site-packages/appium/webdriver/webdriver.py\", line 320, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)\n  File \"/home/manikanta/PycharmProjects/pythonProject_info/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 438, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/home/manikanta/PycharmProjects/pythonProject_info/venv/lib/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py\", line 290, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/home/manikanta/PycharmProjects/pythonProject_info/venv/lib/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py\", line 311, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"/home/manikanta/PycharmProjects/pythonProject_info/venv/lib/python3.8/site-packages/urllib3/request.py\", line 78, in request\n    return self.request_encode_body(\n  File \"/home/manikanta/PycharmProjects/pythonProject_info/venv/lib/python3.8/site-packages/urllib3/request.py\", line 170, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"/home/manikanta/PycharmProjects/pythonProject_info/venv/lib/python3.8/site-packages/urllib3/poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/home/manikanta/PycharmProjects/pythonProject_info/venv/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"/home/manikanta/PycharmProjects/pythonProject_info/venv/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"/home/manikanta/PycharmProjects/pythonProject_info/venv/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"/home/manikanta/PycharmProjects/pythonProject_info/venv/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n  File \"/home/manikanta/PycharmProjects/pythonProject_info/venv/lib/python3.8/site-packages/urllib3/util/retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1678360618185, "stop": 1678360618187}], "start": 1678360618185, "stop": 1678360618654}